FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Bicep
RUN curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 && \
    chmod +x ./bicep && \
    sudo mv ./bicep /usr/local/bin/bicep


# Install PowerShell
RUN apt-get install -y powershell

# Install Ansible
RUN pip3 install ansible

# Install GitHub CLI
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0 && \
    apt-add-repository https://cli.github.com/packages && \
    apt-get update && \
    apt-get install -y gh
